name: Deploy ComisionesGO to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Pages
        uses: actions/configure-pages@v4

      - name: Subir archivos al artefacto de Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'  # publica desde la raíz

      - name: Desplegar en GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
